// Malena Aguiar
const recipeDetails = [
  {
    id: "recipe1",
    title: "Delicious Pasta",
    image: "/images/pasta.jpg",
    description: "A mouthwatering pasta recipe that will satisfy your taste buds.",
    preparationTime: "45 minutes",
    servings: "2",
    equipment: "Pot, Pan, Colander",
    instructions: [
      "Boil water in a pot and cook pasta.",
      "In a pan, sauté garlic and tomatoes.",
      "Toss cooked pasta in the pan.",
      "Season with salt, pepper, and herbs.",
      "Serve hot and enjoy!",
    ],
    ingredients: [
      "200g pasta",
      "2 cloves garlic",
      "1 cup tomatoes",
      "Salt and pepper to taste",
      "Fresh herbs",
    ],
  },
  {
    id: "recipe2",
    title: "Gourmet Burger",
    image: "/images/burger.jpg",
    description: "Sink your teeth into this scrumptious gourmet burger.",
    preparationTime: "40 minutes",
    servings: "1",
    equipment: "Grill, Mixing Bowl",
    instructions: [
      "Prepare burger patty with minced meat and seasonings.",
      "Grill the patty to desired doneness.",
      "Assemble burger with toppings and sauces.",
      "Serve with fries or side salad.",
    ],
    ingredients: [
      "150g minced meat",
      "Burger bun",
      "Lettuce, tomato, onion",
      "Cheese",
      "Sauces of your choice",
    ],
  },
  {
    id: "recipe3",
    title: "Savory Pizza",
    image: "/images/pizza.jpg",
    description: "A classic pizza recipe with a variety of delicious toppings.",
    preparationTime: "60 minutes",
    servings: "4",
    equipment: "Oven, Pizza Stone",
    instructions: [
      "Prepare pizza dough and let it rise.",
      "Roll out the dough and spread tomato sauce.",
      "Add cheese and your favorite toppings.",
      "Bake in a preheated oven until crust is golden.",
      "Slice and enjoy!",
    ],
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Mozzarella cheese",
      "Pepperoni, mushrooms, bell peppers",
      "Herbs and spices",
    ],
  },
  {
    id: "recipe4",
    title: "Creamy Soup",
    image: "/images/soup.jpg",
    description: "Warm up with a bowl of comforting and creamy soup.",
    preparationTime: "35 minutes",
    servings: "6",
    equipment: "Pot, Blender",
    instructions: [
      "Sauté onions and garlic in a pot.",
      "Add chopped vegetables and broth.",
      "Simmer until vegetables are tender.",
      "Blend the soup until smooth.",
      "Return to the pot, add cream, and season.",
      "Heat gently and serve.",
    ],
    ingredients: [
      "2 onions",
      "2 cloves garlic",
      "Assorted vegetables",
      "Vegetable or chicken broth",
      "Heavy cream",
      "Salt and pepper to taste",
    ],
  },
  {
    id: "recipe5",
    title: "Chocolate Cookies",
    image: "/images/cookies.jpg",
    description: "Indulge in these rich and fudgy chocolate cookies.",
    preparationTime: "25 minutes",
    servings: "24",
    equipment: "Oven, Baking Sheet",
    instructions: [
      "Cream butter and sugar in a mixing bowl.",
      "Add eggs and vanilla, mix well.",
      "In another bowl, whisk dry ingredients.",
      "Gradually add dry ingredients to wet mixture.",
      "Fold in chocolate chips.",
      "Drop spoonfuls of dough on baking sheet.",
      "Bake in preheated oven until golden.",
      "Let cool and enjoy!",
    ],
    ingredients: [
      "1 cup butter",
      "1 cup granulated sugar",
      "2 eggs",
      "1 tsp vanilla extract",
      "2 cups all-purpose flour",
      "1/2 cup cocoa powder",
      "1 tsp baking soda",
      "1/4 tsp salt",
      "2 cups chocolate chips",
    ],
  },
  {
    id: "recipe6",
    title: "Healthy Salad",
    image: "/images/salad.jpg",
    description: "A nutritious and refreshing salad packed with fresh ingredients.",
    preparationTime: "15 minutes",
    servings: "2",
    equipment: "Mixing Bowl, Salad Spinner",
    instructions: [
      "Wash and dry lettuce and vegetables.",
      "Chop vegetables and combine in a bowl.",
      "Prepare vinaigrette dressing with olive oil, vinegar, and herbs.",
      "Toss salad with dressing.",
      "Add nuts or seeds for crunch.",
      "Serve immediately and enjoy!",
    ],
    ingredients: [
      "Lettuce, spinach, arugula",
      "Assorted vegetables (tomato, cucumber, bell pepper, etc.)",
      "Nuts or seeds (optional)",
      "Olive oil",
      "Vinegar (balsamic, red wine, etc.)",
      "Herbs and seasonings",
    ],
  },
  {
    id: "recipe7",
    title: "Fruit Smoothie",
    image: "/images/smoothie.jpg",
    description: "Stay refreshed with a delicious and vibrant fruit smoothie.",
    preparationTime: "10 minutes",
    servings: "1",
    equipment: "Blender",
    instructions: [
      "Chop fresh fruits of your choice.",
      "Add fruits, yogurt, and a splash of juice to blender.",
      "Blend until smooth.",
      "Adjust consistency with more juice if needed.",
      "Pour into a glass and enjoy!",
    ],
    ingredients: [
      "Assorted fresh fruits (banana, berries, mango, etc.)",
      "Yogurt",
      "Fruit juice (orange, apple, etc.)",
    ],
  },
  {
    id: "recipe8",
    title: "Stuffed Chicken",
    image: "/images/chicken.jpg",
    description: "Delight your taste buds with juicy and flavorful stuffed chicken.",
    preparationTime: "50 minutes",
    servings: "2",
    equipment: "Oven, Baking Dish",
    instructions: [
      "Butterfly chicken breasts to create pockets.",
      "Prepare stuffing with herbs, cheese, and breadcrumbs.",
      "Stuff mixture into chicken pockets.",
      "Secure with toothpicks.",
      "Season chicken with salt, pepper, and herbs.",
      "Bake in preheated oven until cooked through.",
      "Remove toothpicks before serving.",
    ],
    ingredients: [
      "2 boneless chicken breasts",
      "Fresh herbs (rosemary, thyme, etc.)",
      "Cheese (mozzarella, feta, etc.)",
      "Breadcrumbs",
      "Salt and pepper to taste",
    ],
  },
  {
    id: "recipe9",
    title: "Homemade Sushi",
    image: "/images/sushi.jpg",
    description: "Roll your own sushi with fresh ingredients and creativity.",
    preparationTime: "60 minutes",
    servings: "4",
    equipment: "Sushi Rolling Mat, Rice Cooker",
    instructions: [
      "Prepare sushi rice and let it cool.",
      "Lay seaweed sheet on sushi mat.",
      "Spread rice evenly on seaweed.",
      "Add sliced fish, vegetables, and avocado.",
      "Roll tightly using the mat.",
      "Slice into bite-sized pieces.",
      "Serve with soy sauce and wasabi.",
    ],
    ingredients: [
      "Sushi rice",
      "Seaweed sheets",
      "Assorted fish (salmon, tuna, etc.)",
      "Vegetables (cucumber, avocado, etc.)",
      "Soy sauce",
      "Wasabi",
    ],
  },
  {
    id: "recipe10",
    title: "Classic Pancakes",
    image: "/images/pancakes.jpg",
    description: "Start your day with fluffy and golden classic pancakes.",
    preparationTime: "30 minutes",
    servings: "4",
    equipment: "Skillet, Mixing Bowl",
    instructions: [
      "In a mixing bowl, whisk together dry ingredients.",
      "Add milk, eggs, and melted butter, mix until smooth.",
      "Heat skillet over medium heat.",
      "Pour batter onto skillet to form pancakes.",
      "Cook until bubbles form on the surface.",
      "Flip and cook until golden on both sides.",
      "Serve with your favorite toppings.",
    ],
    ingredients: [
      "1 cup all-purpose flour",
      "2 tbsp sugar",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "3/4 cup milk",
      "1 egg",
      "2 tbsp melted butter",
      "Toppings of your choice (maple syrup, fruits, etc.)",
    ],
  },
  {
    id: "recipe11",
    title: "Mouthwatering Tacos",
    image: "/images/tacos.jpg",
    description: "Savor the flavors of these tacos filled with delicious ingredients.",
    preparationTime: "40 minutes",
    servings: "3",
    equipment: "Skillet, Taco Shells",
    instructions: [
      "Heat skillet over medium heat.",
      "Cook ground meat with taco seasoning until browned.",
      "Warm taco shells in the oven.",
      "Assemble tacos with meat, cheese, lettuce, and toppings.",
      "Drizzle with sour cream and salsa.",
      "Serve immediately and enjoy!",
    ],
    ingredients: [
      "300g ground meat (beef, chicken, etc.)",
      "Taco seasoning",
      "Taco shells",
      "Shredded cheese",
      "Lettuce, tomato, onion",
      "Sour cream, salsa",
    ],
  },
  {
    id: "recipe12",
    title: "Refreshing Lemonade",
    image: "/images/lemonade.jpg",
    description: "Quench your thirst with a glass of refreshing homemade lemonade.",
    preparationTime: "15 minutes",
    servings: "6",
    equipment: "Pitcher, Citrus Juicer",
    instructions: [
      "Juice lemons to get fresh lemon juice.",
      "In a pitcher, combine lemon juice and sugar.",
      "Add water and stir until sugar is dissolved.",
      "Add ice cubes and lemon slices.",
      "Stir well and refrigerate until chilled.",
      "Serve in glasses with extra ice.",
    ],
    ingredients: [
      "4-6 lemons",
      "1 cup granulated sugar",
      "Water",
      "Ice cubes",
      "Lemon slices",
    ],
  },
];

export default recipeDetails;
